version: '3'

services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=prediction_app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@Niranjana99
    container_name: postgres_db

  backend:
    build:
      context: ./prediction-app-backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db 

  frontend:
    build:
      context: ./prediction-app-frontend/predictionAPI
    volumes:
      - react_build:/prediction-app-frontend/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/prediction-app-frontend
    depends_on:
      - backend
      - frontend
volumes:
  react_build: