FROM python:3.8-slim
ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip

RUN useradd --system --user-group app

WORKDIR /prediction-app-backend
COPY ./prediction-app-backend/requirements.txt requirements.txt
RUN pip install --quiet --no-cache-dir -r requirements.txt

WORKDIR /prediction-app-frontend

COPY ./prediction-app-frontend/package.json /prediction-app-frontend

COPY ./entrypoint-prod.sh /prediction-app-backend
RUN sed -i 's/\r$//g' /prediction-app-backend/entrypoint.sh
RUN chmod +x /prediction-app-backend/entrypoint.sh

EXPOSE 5001

RUN ["chmod", "+x", "/prediction-app-backend/entrypoint.sh"]
ENTRYPOINT ["/prediction-app-backend/entrypoint.sh"]